# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Web-MicroID
version:      0.02
version_from: lib/Web/MicroID.pm
installdirs:  site
requires:
    Digest::MD5:                   2
    Digest::SHA1:                  2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
